### ISSUE TITLE
Pooltool.io not recognizing my staking address. 

### ISSUE THREAD

**Issue by Ankney67** [papacarp/pooltool.io#165]
I claimed my staking address back in Feb. 2021 and have been using the same one. 
After todays epoch when I paste my staking address into the Reward Data for Taxes field it states  the address is not valid - see attachment.
When I look at my profile in pooltool.io it is showing that i have not claimed my staking address - see attachment.
When I open the pool address and find my stake address it states that I have claimed it. See attachment
![Screenshot 2022-08-08 201854](https://user-images.githubusercontent.com/110869657/183536482-99ac9f27-49b4-4012-86db-8c21f34221a6.png)
![Screenshot 2022-08-08 200726](https://user-images.githubusercontent.com/110869657/183536508-feb08b15-1b38-4d52-b742-12ff994ce31d.png)

![Screenshot 2022-08-08 200825](https://user-images.githubusercontent.com/110869657/183536497-74050c14-1f38-440d-9f91-1c91f444a20a.png)

.

**Comment by papacarp** [comment]
will take a look in next 24 hours

**Comment by Ankney67** [comment]
Thank you.

**Comment by Ankney67** [comment]
I checked today  and the problem is resolved. Thank you!

**Comment by papacarp** [comment]
looks like you have claimed it under the old methodology. we migrated to
using logins just with your stake_key instead of email addresses for
privacy reasons.  The reason it's still showing as claimed is because we
used the same cookie name in the website to show which addresses you have
claimed under both the old and new login methodology.  Probably a bad call
on our our part but in a year and a half you are the first to notice so
maybe not a huge deal.

Recommend you go ahead and sign up for a new account and claim them again
if you want them all in one place.

Mike
